/**
 * Image Generation Extension - Recreates Codex's image generation feature
 *
 * Generates images using local tools without requiring API keys.
 * Falls back through multiple methods:
 *   1. Python with Pillow (simple image creation)
 *   2. ImageMagick (convert) if available
 *   3. SVG generation (always works)
 *
 * Commands:
 *   /imagegen <prompt>    - Generate an image from a text prompt
 *
 * Tools:
 *   image_generate        - LLM can call to generate images
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as cp from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

function execCommand(cmd: string, args: string[], timeout = 30000): Promise<{ stdout: string; stderr: string; success: boolean }> {
	return new Promise((resolve) => {
		try {
			const proc = cp.spawn(cmd, args, { timeout });
			let stdout = "";
			let stderr = "";
			proc.stdout?.on("data", (d) => (stdout += d.toString()));
			proc.stderr?.on("data", (d) => (stderr += d.toString()));
			proc.on("close", (code) => resolve({ stdout, stderr, success: code === 0 }));
			proc.on("error", () => resolve({ stdout, stderr: "Command not found", success: false }));
		} catch {
			resolve({ stdout: "", stderr: "Failed to spawn", success: false });
		}
	});
}

async function generateWithPython(prompt: string, outputPath: string): Promise<boolean> {
	const safePrompt = JSON.stringify(prompt.slice(0, 200));
	const safeOutputPath = JSON.stringify(outputPath);
	const script = `
import sys, json, os
try:
    from PIL import Image, ImageDraw, ImageFont
    img = Image.new('RGB', (800, 600), color='#1a1a2e')
    draw = ImageDraw.Draw(img)
    # Draw a simple colored rectangle
    for i in range(10):
        hue = (i * 36) % 360
        import colorsys
        r, g, b = colorsys.hsv_to_rgb(hue/360, 0.3, 0.15)
        draw.rectangle([i*80, 500, (i+1)*80, 600], fill=(int(r*255), int(g*255), int(b*255)))
    # Draw text
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 24)
    except:
        font = ImageFont.load_default()
    draw.text((20, 20), "Image Generation", fill='#e0e0e0', font=font)
    words = ${safePrompt}
    draw.text((20, 60), words, fill='#888888', font=font)
    img.save(${safeOutputPath})
    print("OK")
except Exception as e:
    print(f"ERROR: {e}", file=sys.stderr)
    sys.exit(1)
`;

	const scriptPath = path.join(os.tmpdir(), `pi-imagegen-${Date.now()}.py`);
	try {
		fs.writeFileSync(scriptPath, script);
		const result = await execCommand("python3", [scriptPath], 15000);
		return result.success;
	} finally {
		try { fs.unlinkSync(scriptPath); } catch {}
	}
}

async function generateWithImageMagick(prompt: string, outputPath: string): Promise<boolean> {
	const size = "800x600";
	const bgColor = "#1a1a2e";
	const textColor = "#e0e0e0";
	const label = prompt.slice(0, 80).replace(/['"]/g, "");

	const result = await execCommand("convert", [
		"-size", size,
		`xc:${bgColor}`,
		"-fill", textColor,
		"-font", "Helvetica",
		"-pointsize", "24",
		"-gravity", "northwest",
		"-annotate", "+20+20", "Image Generation",
		"-pointsize", "16",
		"-fill", "#888888",
		"-annotate", "+20+60", label,
		"-fill", "#16213e",
		"-draw", "rectangle 0,500 800,600",
		"-fill", "#0f3460",
		"-draw", "rectangle 80,520 160,600",
		"-fill", "#533483",
		"-draw", "rectangle 240,520 320,600",
		"-fill", "#e94560",
		"-draw", "rectangle 400,520 480,600",
		outputPath,
	]);

	return result.success;
}

function generateSVG(prompt: string): string {
	const words = prompt.slice(0, 100);
	const colors = ["#1a1a2e", "#16213e", "#0f3460", "#533483", "#e94560"];
	return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${colors[0]}"/>
      <stop offset="100%" style="stop-color:${colors[1]}"/>
    </linearGradient>
  </defs>
  <rect width="800" height="600" fill="url(#bg)"/>
  <rect x="0" y="520" width="800" height="80" fill="${colors[2]}" opacity="0.5"/>
  <circle cx="100" cy="100" r="60" fill="${colors[3]}" opacity="0.3"/>
  <circle cx="700" cy="300" r="120" fill="${colors[4]}" opacity="0.2"/>
  <circle cx="400" cy="150" r="80" fill="${colors[3]}" opacity="0.15"/>
  <text x="30" y="50" font-family="sans-serif" font-size="24" fill="${colors[2]}">Image Generation</text>
  <text x="30" y="85" font-family="sans-serif" font-size="14" fill="#888888">${words}</text>
  <text x="30" y="560" font-family="monospace" font-size="11" fill="#666">Generated by pi image-gen</text>
</svg>`;
}

async function generateImage(prompt: string): Promise<{ success: boolean; path?: string; content?: string; error?: string }> {
	const outputDir = path.join(os.tmpdir(), "pi-imagegen");
	if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

	const timestamp = Date.now();
	const pngPath = path.join(outputDir, `generated-${timestamp}.png`);
	const svgPath = path.join(outputDir, `generated-${timestamp}.svg`);

	// Try Python+Pillow first
	const pyResult = await generateWithPython(prompt, pngPath);
	if (pyResult && fs.existsSync(pngPath)) {
		return { success: true, path: pngPath };
	}

	// Try ImageMagick
	const imResult = await generateWithImageMagick(prompt, pngPath);
	if (imResult && fs.existsSync(pngPath)) {
		return { success: true, path: pngPath };
	}

	// Fall back to SVG
	const svgContent = generateSVG(prompt);
	fs.writeFileSync(svgPath, svgContent);
	return { success: true, path: svgPath, content: svgContent };
}

export default function (pi: ExtensionAPI) {
	// ── Tool: image_generate ──────────────────────────────────────────────

	pi.registerTool({
		name: "image_generate",
		label: "Generate Image",
		description:
			"Generate an image from a text description. Creates images using local tools (Python Pillow, ImageMagick, or SVG fallback). " +
			"No API key required. Returns the path to the generated image file.",
		promptSnippet: "Generate an image from a text description",
		promptGuidelines: [
			"Use image_generate when the user asks to create an image, icon, banner, or illustration.",
			"Generated images are saved to a temp directory. Tell the user the file path.",
		],
		parameters: Type.Object({
			prompt: Type.String({
				description: "Description of the image to generate (what it should look like, colors, style)",
			}),
		}),

		async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
			const result = await generateImage(params.prompt);

			if (!result.success) {
				return {
					content: [
						{
							type: "text",
							text: `Image generation failed: ${result.error || "Unknown error"}. SVG fallback was created.`,
						},
					],
					details: { success: false, error: result.error },
				};
			}

			// Read the image as base64 if it's a PNG
			let imageData = "";
			if (result.path && fs.existsSync(result.path)) {
				const ext = path.extname(result.path).toLowerCase();
				if (ext === ".png") {
					const buffer = fs.readFileSync(result.path);
					imageData = buffer.toString("base64");
				} else if (ext === ".svg" || result.content) {
					imageData = Buffer.from(result.content || "").toString("base64");
				}
			}

			return {
				content: [
					{
						type: "text",
						text: `Image generated successfully!\nFile: ${result.path}\nFormat: ${path.extname(result.path || "").slice(1) || "svg"}\nPrompt: "${params.prompt}"`,
					},
					...(imageData
						? [
								{
									type: "image",
									source: {
										type: "base64",
										mediaType: result.path?.endsWith(".svg")
											? "image/svg+xml"
											: "image/png",
										data: imageData,
									},
								} as any,
							]
						: []),
				],
				details: {
					success: true,
					path: result.path,
					method: result.path?.endsWith(".svg") ? "svg" : "image",
				},
			};
		},
	});

	// ── Command: /imagegen ────────────────────────────────────────────────

	pi.registerCommand("imagegen", {
		description: "Generate an image from a text prompt (local, no API key)",
		handler: async (args, ctx) => {
			const prompt = (args || "").trim();
			if (!prompt) {
				ctx.ui.notify(
					"Usage: /imagegen <description> - Generate an image from a text prompt",
					"info",
				);
				return;
			}

			ctx.ui.notify("Generating image...", "info");

			const result = await generateImage(prompt);

			if (result.path && fs.existsSync(result.path)) {
				// Open the image
				const ext = path.extname(result.path).toLowerCase();
				try {
					if (process.platform === "darwin") {
						cp.spawn("open", [result.path], { detached: true, stdio: "ignore" }).unref();
					} else if (process.platform === "linux") {
						cp.spawn("xdg-open", [result.path], { detached: true, stdio: "ignore" }).unref();
					} else if (process.platform === "win32") {
						cp.spawn("cmd", ["/c", "start", "", result.path], { detached: true, stdio: "ignore" }).unref();
					}
				} catch {
					// Best effort
				}

				ctx.ui.notify(
					`Image generated: ${result.path} (${ext.slice(1).toUpperCase()})`,
					"info",
				);
			} else {
				ctx.ui.notify("Image generation failed. Install Python Pillow or ImageMagick for better results.", "error");
			}
		},
	});
}
